package in.eko.eps;

import com.google.gson.Gson;
import com.google.gson.JsonSyntaxException;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.regex.Pattern;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

/**
 * Backend-only Java client for Eko Platform Services (EPS) APIs — DMT, AePS, BBPS, KYC and
 * verification — with HMAC request signing built in.
 *
 * <p>Port of {@code packages/sdk-js/src/client.ts} and {@code packages/sdk-php/src/EpsClient.php}.
 * The signing algorithm, validation rules and error message formats are fixed by {@code
 * docs/sdk-golden-vector.md} — every SDK language must agree byte for byte.
 *
 * <p>Never run this anywhere a browser or mobile app can reach: {@code accessKey} signs every
 * request and must stay server-side.
 */
public final class EpsClient {

	/**
	 * Name of the single form field carrying every non-file value as one JSON object. Eko's upload
	 * APIs do not take a form field per parameter. Mirrors {@code MULTIPART_JSON_FIELD} in the
	 * website's {@code src/lib/data/api-specs-common.ts}.
	 */
	public static final String MULTIPART_JSON_FIELD = "form-data";

	private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(30);
	private static final Pattern NUMBER_RE = Pattern.compile("^-?\\d+(\\.\\d+)?$");
	private static final Pattern INTEGER_RE = Pattern.compile("^-?\\d+$");
	/**
	 * serializeNulls is REQUIRED for conformance, not a preference: Gson drops null fields by
	 * default, while JSON.stringify, json_encode, json.dumps and encoding/json all keep them. A
	 * null nested inside a value is real data (see docs/sdk-golden-vector.md), so dropping it would
	 * put different bytes on the wire from every other SDK.
	 */
	private static final Gson GSON = new com.google.gson.GsonBuilder().serializeNulls().create();
	private static final SecureRandom RANDOM = new SecureRandom();

	/** Client-side failure: unknown slug, missing param, bad type, bad config. */
	public static class EpsException extends RuntimeException {
		public EpsException(String message) {
			super(message);
		}

		public EpsException(String message, Throwable cause) {
			super(message, cause);
		}
	}

	/**
	 * Non-2xx response from EPS. The decoded envelope is kept on {@link #body} so callers can
	 * inspect it, but this is thrown rather than returned: an auth or infrastructure failure must
	 * never be mistaken for a successful call.
	 */
	public static final class EpsHttpException extends EpsException {
		public final int status;
		public final String url;
		public final Map<String, Object> body;
		public final String raw;

		EpsHttpException(int status, String url, Map<String, Object> body, String raw) {
			super("EPS request to " + url + " failed with HTTP " + status + ".");
			this.status = status;
			this.url = url;
			this.body = body;
			this.raw = raw;
		}
	}

	/** An in-memory upload, for callers that do not have the bytes on disk. */
	public record EpsFile(String name, byte[] content) {}

	/** The resolved wire target for one call — everything but the sending. */
	public record Target(
			String method, String url, byte[] body, Map<String, String> headers, boolean multipart) {}

	private record Param(String name, String type, boolean required) {}

	private record Endpoint(
			String slug, String method, String path, List<Param> params, List<String> requiredParams) {}

	private record Environment(String id, String baseUrl) {}

	private record Surface(List<Environment> environments, List<Endpoint> endpoints) {}

	/**
	 * The baked API surface, loaded once from the classpath. Generated by {@code
	 * scripts/bake-surface.mjs} and packaged from {@code data/} (see pom.xml) — a missing resource
	 * means the jar was built incorrectly.
	 */
	private static final Surface SURFACE = loadSurface();

	private static Surface loadSurface() {
		try (InputStream in = EpsClient.class.getResourceAsStream("/sdk-surface.json")) {
			if (in == null) {
				throw new EpsException(
						"EPS SDK surface not found on the classpath (/sdk-surface.json). "
								+ "The package is built incorrectly (run `npm run build` to bake it).");
			}
			Surface surface =
					GSON.fromJson(new String(in.readAllBytes(), StandardCharsets.UTF_8), Surface.class);
			if (surface == null || surface.environments() == null || surface.endpoints() == null) {
				throw new EpsException("EPS SDK surface is invalid or corrupt.");
			}
			return surface;
		} catch (IOException e) {
			throw new UncheckedIOException(e);
		}
	}

	private final String developerKey;
	private final String accessKey;
	private final String baseUrl;
	private final String initiatorId;
	private final String userCode;
	private final HttpClient http;
	/** Test-only clock injection (ms since the epoch); not part of the public surface. */
	java.util.function.LongSupplier now = System::currentTimeMillis;

	private EpsClient(Builder builder) {
		this.developerKey = builder.developerKey;
		this.accessKey = builder.accessKey;
		this.initiatorId = builder.initiatorId;
		this.userCode = builder.userCode;
		this.http =
				builder.httpClient != null
						? builder.httpClient
						: HttpClient.newBuilder().connectTimeout(DEFAULT_TIMEOUT).build();
		this.baseUrl =
				SURFACE.environments().stream()
						.filter(e -> e.id().equals(builder.environment))
						.findFirst()
						.orElseThrow(
								() -> new EpsException("Unknown environment \"" + builder.environment + "\"."))
						.baseUrl();
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * Builds a client. {@code initiatorId} / {@code userCode} are near-constant per developer, so
	 * they are set once here and injected into every call; pass either in a call's params to
	 * override (including an explicit null to clear one).
	 */
	public static final class Builder {
		private String developerKey;
		private String accessKey;
		private String environment;
		private String initiatorId;
		private String userCode;
		private HttpClient httpClient;

		public Builder developerKey(String v) {
			this.developerKey = v;
			return this;
		}

		public Builder accessKey(String v) {
			this.accessKey = v;
			return this;
		}

		/** An environment id from the surface: {@code sandbox} or {@code production}. */
		public Builder environment(String v) {
			this.environment = v;
			return this;
		}

		public Builder initiatorId(String v) {
			this.initiatorId = v;
			return this;
		}

		public Builder userCode(String v) {
			this.userCode = v;
			return this;
		}

		/** Supply your own client to control timeouts, proxies or redirects. */
		public Builder httpClient(HttpClient v) {
			this.httpClient = v;
			return this;
		}

		public EpsClient build() {
			return new EpsClient(this);
		}
	}

	/**
	 * secret-key = base64(HMAC-SHA256(timestamp, base64(access_key))).
	 *
	 * <p>The HMAC key is the base64 <em>string's</em> bytes — the encoded text, not the decoded key.
	 * See docs/sdk-golden-vector.md.
	 */
	public static String sign(String accessKey, String timestamp) {
		try {
			String encodedKey =
					Base64.getEncoder().encodeToString(accessKey.getBytes(StandardCharsets.UTF_8));
			Mac mac = Mac.getInstance("HmacSHA256");
			mac.init(new SecretKeySpec(encodedKey.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
			return Base64.getEncoder()
					.encodeToString(mac.doFinal(timestamp.getBytes(StandardCharsets.UTF_8)));
		} catch (java.security.GeneralSecurityException e) {
			throw new EpsException("HMAC-SHA256 unavailable", e);
		}
	}

	/** True for a number, excluding Boolean. */
	private static boolean isNumber(Object value) {
		return value instanceof Number n
				&& !(n instanceof Double d && (d.isNaN() || d.isInfinite()))
				&& !(n instanceof Float f && (f.isNaN() || f.isInfinite()));
	}

	/** Whole numbers count as integers, matching JS {@code Number.isInteger}. */
	private static boolean isWholeNumber(Object value) {
		if (!isNumber(value)) return false;
		double d = ((Number) value).doubleValue();
		return d == Math.rint(d);
	}

	/**
	 * A readable local file, or an in-memory {@link EpsFile}. Paths must exist, matching the PHP
	 * SDK: a typo'd path is caught before the request is signed rather than at read time.
	 */
	private static boolean isFileValue(Object value) {
		if (value instanceof EpsFile) return true;
		if (value instanceof Path p) return Files.isRegularFile(p);
		if (value instanceof java.io.File f) return f.isFile();
		return value instanceof String s && Files.isRegularFile(Path.of(s));
	}

	/**
	 * Lenient, coercion-aware type check against a spec type. Only present values are checked
	 * (presence is enforced separately). Unknown types pass. The wire sends everything as strings,
	 * so numeric/boolean strings are accepted.
	 */
	private static boolean matchesType(String type, Object value) {
		return switch (type) {
				// Strings and numbers (which coerce cleanly); not booleans/objects.
			case "string" -> value instanceof String || isNumber(value);
			case "file" -> isFileValue(value);
			case "number" -> isNumber(value)
					|| (value instanceof String s && NUMBER_RE.matcher(s).matches());
			case "integer" -> isWholeNumber(value)
					|| (value instanceof String s && INTEGER_RE.matcher(s).matches());
			case "boolean" -> value instanceof Boolean || "true".equals(value) || "false".equals(value);
				// unknown/unsupported spec type -> not enforced
			default -> true;
		};
	}

	/**
	 * Stringify a value for a URL path token or query param, matching JavaScript {@code
	 * String(value)} so every SDK puts identical bytes on the wire: lowercase booleans, and no
	 * trailing ".0" on whole numbers (Java's own {@code Double.toString(5.0)} would emit "5.0").
	 */
	private static String wireString(Object value) {
		if (value == null) return "null";
		if (value instanceof String s) return s;
		if (isWholeNumber(value)) {
			double d = ((Number) value).doubleValue();
			if (d >= Long.MIN_VALUE && d <= Long.MAX_VALUE) return Long.toString((long) d);
		}
		return String.valueOf(value);
	}

	private static Endpoint endpointFor(String slug) {
		return SURFACE.endpoints().stream()
				.filter(e -> e.slug().equals(slug))
				.findFirst()
				.orElseThrow(() -> new EpsException("Unknown endpoint slug \"" + slug + "\"."));
	}

	/**
	 * Signed auth headers. Multipart callers get no {@code content-type} here — the
	 * boundary-carrying value is set when the body is encoded.
	 */
	public Map<String, String> buildHeaders(boolean multipart) {
		String timestamp = Long.toString(now.getAsLong());
		Map<String, String> headers = new LinkedHashMap<>();
		headers.put("developer_key", developerKey);
		headers.put("secret-key", sign(accessKey, timestamp));
		headers.put("secret-key-timestamp", timestamp);
		if (!multipart) headers.put("content-type", "application/json");
		return headers;
	}

	/**
	 * Multipart body: one {@code form-data} part holding every non-file value as JSON, then a part
	 * per upload — the order the API documents. Null values are dropped (a form field has no null
	 * encoding), while nulls nested inside a value survive the JSON.
	 */
	static byte[] encodeMultipart(
			Map<String, Object> values, Set<String> fileParams, String boundary) {
		Map<String, Object> payload = new TreeMap<>();
		List<EpsFile> uploads = new ArrayList<>();
		List<String> uploadFields = new ArrayList<>();
		// Sorted: Java map iteration order must not decide the request bytes.
		for (Map.Entry<String, Object> entry : new TreeMap<>(values).entrySet()) {
			Object value = entry.getValue();
			if (value == null) continue;
			if (!fileParams.contains(entry.getKey())) {
				payload.put(entry.getKey(), value);
				continue;
			}
			uploadFields.add(entry.getKey());
			uploads.add(toFile(entry.getKey(), value));
		}

		var out = new java.io.ByteArrayOutputStream();
		try {
			out.write(("--" + boundary + "\r\n").getBytes(StandardCharsets.UTF_8));
			out.write(
					("Content-Disposition: form-data; name=\"" + MULTIPART_JSON_FIELD + "\"\r\n\r\n")
							.getBytes(StandardCharsets.UTF_8));
			out.write(GSON.toJson(payload).getBytes(StandardCharsets.UTF_8));
			out.write("\r\n".getBytes(StandardCharsets.UTF_8));
			for (int i = 0; i < uploads.size(); i++) {
				EpsFile file = uploads.get(i);
				out.write(("--" + boundary + "\r\n").getBytes(StandardCharsets.UTF_8));
				out.write(
						("Content-Disposition: form-data; name=\""
										+ uploadFields.get(i)
										+ "\"; filename=\""
										+ file.name()
										+ "\"\r\n")
								.getBytes(StandardCharsets.UTF_8));
				out.write("Content-Type: application/octet-stream\r\n\r\n".getBytes(StandardCharsets.UTF_8));
				out.write(file.content());
				out.write("\r\n".getBytes(StandardCharsets.UTF_8));
			}
			out.write(("--" + boundary + "--\r\n").getBytes(StandardCharsets.UTF_8));
		} catch (IOException e) {
			throw new UncheckedIOException(e); // ByteArrayOutputStream does not throw
		}
		return out.toByteArray();
	}

	private static EpsFile toFile(String name, Object value) {
		if (value instanceof EpsFile f) return f;
		Path path =
				value instanceof Path p
						? p
						: value instanceof java.io.File f ? f.toPath() : Path.of(String.valueOf(value));
		try {
			return new EpsFile(path.getFileName().toString(), Files.readAllBytes(path));
		} catch (IOException e) {
			throw new EpsException("Reading upload \"" + name + "\": " + e.getMessage(), e);
		}
	}

	/**
	 * Resolve a slug and params into the signed wire target.
	 *
	 * @throws EpsException on an unknown slug, a missing required param or a type mismatch — before
	 *     anything is signed or sent.
	 */
	public Target resolveTarget(String slug, Map<String, Object> params) {
		Endpoint endpoint = endpointFor(slug);

		// Client-level defaults first; an explicit per-call value wins, including an
		// explicit null that clears one.
		Map<String, Object> merged = new LinkedHashMap<>();
		if (initiatorId != null) merged.put("initiator_id", initiatorId);
		if (userCode != null) merged.put("user_code", userCode);
		if (params != null) merged.putAll(params);

		// Spec-driven guard: every requiredParam must be present and non-null before
		// we sign and send.
		List<String> missing =
				endpoint.requiredParams().stream().filter(p -> merged.get(p) == null).toList();
		if (!missing.isEmpty()) {
			throw new EpsException(
					"Missing required params for \"" + slug + "\": " + String.join(", ", missing) + ".");
		}

		// Type guard: every provided param known to the spec must match its type.
		// Unknown params (not in the surface) pass through untouched.
		List<String> badTypes =
				endpoint.params().stream()
						.filter(p -> merged.get(p.name()) != null && !matchesType(p.type(), merged.get(p.name())))
						.map(p -> p.name() + " (expected " + p.type() + ")")
						.toList();
		if (!badTypes.isEmpty()) {
			throw new EpsException(
					"Invalid param types for \"" + slug + "\": " + String.join(", ", badTypes) + ".");
		}

		// A type:"file" param flips the whole request to multipart/form-data.
		Set<String> fileParams = new HashSet<>();
		for (Param p : endpoint.params()) if ("file".equals(p.type())) fileParams.add(p.name());
		boolean multipart = !fileParams.isEmpty();

		// Path params (e.g. {customer_id}) fill the URL; the rest become the query
		// string on GET, a multipart body when the endpoint has file uploads, or the
		// JSON body on every other method.
		String path = endpoint.path();
		Map<String, Object> rest = new TreeMap<>();
		for (Map.Entry<String, Object> entry : merged.entrySet()) {
			String token = "{" + entry.getKey() + "}";
			if (path.contains(token)) {
				path = path.replace(token, encode(wireString(entry.getValue())));
			} else {
				rest.put(entry.getKey(), entry.getValue());
			}
		}

		String url = baseUrl + path;
		Map<String, String> headers = buildHeaders(multipart);
		byte[] body = null;
		if ("GET".equals(endpoint.method())) {
			StringBuilder query = new StringBuilder();
			for (Map.Entry<String, Object> entry : rest.entrySet()) {
				if (query.length() > 0) query.append('&');
				query.append(encode(entry.getKey())).append('=').append(encode(wireString(entry.getValue())));
			}
			if (query.length() > 0) url += (url.contains("?") ? "&" : "?") + query;
		} else if (multipart) {
			String boundary = "----EpsSdkBoundary" + new java.math.BigInteger(128, RANDOM).toString(16);
			body = encodeMultipart(rest, fileParams, boundary);
			headers.put("content-type", "multipart/form-data; boundary=" + boundary);
		} else {
			body = GSON.toJson(rest).getBytes(StandardCharsets.UTF_8);
		}
		return new Target(endpoint.method(), url, body, headers, multipart);
	}

	private static String encode(String value) {
		return URLEncoder.encode(value, StandardCharsets.UTF_8);
	}

	/**
	 * Sign and send one endpoint call, returning the decoded response envelope.
	 *
	 * @throws EpsHttpException on a non-2xx response; a body that is not JSON is an error, never a
	 *     silent empty map.
	 */
	public Map<String, Object> call(String slug, Map<String, Object> params) {
		Target target = resolveTarget(slug, params);
		HttpRequest.Builder request =
				HttpRequest.newBuilder(URI.create(target.url())).timeout(DEFAULT_TIMEOUT);
		target.headers().forEach(request::header);
		request.method(
				target.method(),
				target.body() == null
						? HttpRequest.BodyPublishers.noBody()
						: HttpRequest.BodyPublishers.ofByteArray(target.body()));

		HttpResponse<String> response;
		try {
			response = http.send(request.build(), HttpResponse.BodyHandlers.ofString());
		} catch (IOException e) {
			throw new EpsException("EPS request to " + target.url() + " failed: " + e.getMessage(), e);
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			throw new EpsException("EPS request to " + target.url() + " was interrupted", e);
		}

		return handleResponse(response.statusCode(), target.url(), response.body());
	}

	/**
	 * Turn one raw response into the envelope callers expect. Package-private so the response
	 * contract shared by all five SDKs (see docs/sdk-golden-vector.md) is unit-testable without
	 * stubbing the abstract {@link HttpClient}.
	 *
	 * @throws EpsHttpException on any non-2xx response; the decoded envelope is on {@code body}.
	 * @throws EpsException when a 2xx body is not JSON — never a silent empty map.
	 */
	static Map<String, Object> handleResponse(int status, String url, String raw) {
		Map<String, Object> envelope = decodeOrNull(raw);
		if (status < 200 || status >= 300) {
			throw new EpsHttpException(status, url, envelope, raw);
		}
		if (envelope == null) {
			throw new EpsException("EPS response from " + url + " was not valid JSON.");
		}
		return envelope;
	}

	private static Map<String, Object> decodeOrNull(String raw) {
		try {
			return GSON.fromJson(raw, new TypeToken<Map<String, Object>>() {}.getType());
		} catch (JsonSyntaxException e) {
			return null;
		}
	}
}
